# Generated by Django 3.2.12 on 2023-03-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_open_time_store_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='saturated_fats_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar_percentage',
            field=models.FloatField(default=0),
        ),
    ]
