# Generated by Django 3.2.12 on 2023-03-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20230320_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
