# Generated by Django 4.0.2 on 2023-03-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_store_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='schedule',
        ),
        migrations.AddField(
            model_name='store',
            name='close_time',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AddField(
            model_name='store',
            name='open_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
